### ISSUE TITLE
Question: SSM Automation Documents

### ISSUE THREAD

**Issue by magrossm** [aws/amazon-ssm-agent#187]
Dear Contributors,

I have a question regarding SSM Automation Documents and Conditional Scripting.
I understand the use of aws:branch and different choices and outputs. 

**Workflow**
There is a check if the machine is online and if not, please start the instance (byin then powershell code gets executed. Afterwards I want to stop the instance based on the fact if it was online/offline or started before. I do not know how conditionally fulfill this requirement. I want basically a condition at the bottom that shutdowns machine machine was offline and started.
I do not know if to go by ec2 api and instancestatechange / previous state or by setting temporary tags.

Glad for any help. 

```
---
description: "...."
schemaVersion: "0.3"
assumeRole: "{{ AutomationAssumeRole }}"
parameters:
  InstanceId:
    type: "StringList"
    description: "(Optional) EC2 Instance(s)"
  AutomationAssumeRole:
    type: "String"
    description: "(Optional) The ARN of the role that allows Automation to perform the actions on your behalf."
    default: ""
mainSteps:
- name: defineMachine
  action: aws:executeAwsApi
  inputs:
    Service: ec2
    Api: DescribeInstances
  outputs:
  - name: state
    Selector: "$.Reservations[0].Instances[0].InstanceState.name"
    Type: String
  - name: instanceId
    Selector: "$.Reservations[0].Instances[0].instanceId"
    Type: String
- name: stateConditional
  action: aws:branch
  inputs:
    Choices:
    - NextStep: startedInstance
      Variable: "{{defineMachine.state}}"
      StringEquals: stopped
    - NextStep: defineMachinePlatform
      Variable: "{{defineMachine.state}}"
      StringEquals: running
    Default:
      Sleep
- name: startedInstance
  action: aws:executeAwsApi
  inputs:
    Service: ec2
    Api: StartInstances
    InstanceId: "{{defineMachine.instanceId}}"
  outputs:
  - name: previousState
    Selector: "$.instancesSet[0].previousState[0].name"
    Type: String
  nextStep: waitForSSMConnection
- name: waitForSSMConnection
  action: aws:waitForAwsResourceProperty
  inputs:
    Service: ssm
    Api: DescribeInstanceInformation
    Propertyselector: "$.InstanceInformationList[0].PingStatus"
    DesiredValues:
    - Online
  nextStep: defineMachinePlatform
- name: defineMachinePlatform
  action: aws:executeAwsApi
  inputs:
    Service: ssm
    Api: DescribeInstanceInformation
  outputs:
  - name: platform
    Selector: "$.InstanceInformationList[0].PlatformType"
    Type: String
- name: ChooseOS
  action: aws:branch
  inputs:
    Choices:
    - NextStep: prepareForPatchSysPrep
      Variable: "{{defineMachinePlatform.platform}}"
      StringEquals: Windows
    - NextStep: stillToDefine
      Variable: "{{defineMachinePlatform.platform}}"
      StringEquals: Linux
    Default:
      Sleep
- name: stillToDefine
  action: #stillToDefine
  inputs: #stillToDefine
  isEnd: True
- name: prepareForPatchSysPrep
  action: aws:runCommand
  inputs:
    DocumentName: AWS-RunPowerShellScript
    Parameters:
      ExecutionTimeout: 600
      Timeout: 60
      Commands:
        .....
- name: installCurrentAwsTools
  action: aws:runCommand
  inputs:
    DocumentName: AWS-InstallApplication
    Parameters:
      Action: Install
      ExecutionTimeout: 600
      Timeout: 60
      Source: ""
- name: checkMaintenanceWindow
  action: aws:runCommand
  inputs:
    DocumentName: AWS-RunPowerShellScript
    Parameters:
      ExecutionTimeout: 600
      Timeout: 60
      Commands:
        ......
- name: defineFurtherState
  action: aws:branch
  inputs:
    Choices:
    - NextStep: stopInstanceIfOfflineBefore
      Variable: "{{startedInstance.previousState}}"
      StringEquals: stopped
    - NextStep: stopAutomation
      Variable: "{{startedInstance.previousState}}"
      StringEquals: running
    Default:
      Sleep
- name: stopInstanceIfOfflineBefore
  action: aws:changeInstanceState
  inputs:
    InstanceIds: "{{defineMachine.instanceId}}"
    CheckStateOnly: false
    DesiredState: stopped
  isEnd: True
- name: stopAutomation
  action: some action.....
```

**Comment by magrossm** [comment]
CORRECTION: The state has to be checked before the platform. A mistake i corrected. But for the question it is not really an issue.

**Comment by nanalakshmanan** [comment]
You can reuse the output of the defineMachine step and add another branch as described below:

````
- name: stateConditional2
  action: aws:branch
  inputs:
    Choices:
    - NextStep: shutdownInstance
      Variable: "{{defineMachine.state}}"
      StringEquals: stopped
    Default:
      Sleep
- name: shudownInstance
...
````
