### ISSUE TITLE
aws:downloadContent fails to clone git repositories when a specific branch is provided via getOptions

### ISSUE THREAD

**Issue by jlgoolsbee** [aws/amazon-ssm-agent#424]
I'm trying to use the `aws:downloadContent` plugin to clone/checkout a specific branch of a git repository, but when configured to do so, the action always fails with an error. This occurs with any repo/branch combination I have tested thus far. Below I've listed a random sampling of repositories, hosts (just to rule out any one git host), and branches; none are the repo I'm attempting to clone, which is private, but all of which exhibit the same error and return successfully if the `getOptions` key/value parameter is removed:

* `{ "repository": "https://github.com/aws/amazon-ssm-agent.git", "getOptions": "branch:mainline" }`
* `{ "repository": "https://gitlab.com/pycqa/flake8.git", "getOptions": "branch:pre-commit-ci-update-config" }`
* `{ "repository": "https://bitbucket.org/atlassianlabs/atlascode.git", "getOptions": "branch:VSCODE-897-testing" }`

Based on my testing, this issue is limited to the `branch` parameter for `getOptions`; specifying a `commitID` works (but is not a workaround for this issue).

**Docs:** https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-plugins.html#aws-downloadContent

**Steps to reproduce:**

1. Create an SSM document with the `aws:downloadContent` plugin
2. Set the `SourceType` parameter to "Git"
3. Set the `SourceInfo` parameter to any git repo with the `getOptions` parameter and a branch name

**Expected behavior:**

The agent clones (or checks out) the specified branch.

**Actual behavior:**

The action fails and throws the error `Cannot checkout: reference not found`.

---

**SSM Agent version:** 3.1.821.0
**Target OS:** Amazon Linux 2

**Example SSM document:**

```yaml
---
schemaVersion: "2.2"
description: Download the configured git repo

parameters:
  SourceInfo:
    default: {}
    displayType: "textarea"
    description: "Specify the information required to access the git repository."
    type: "StringMap"

mainSteps:
  - action: aws:downloadContent
    name: downloadContent
    inputs:
      SourceInfo: "{{ SourceInfo }}"
      SourceType: "Git"
    precondition:
      StringEquals:
        - platformType
        - Linux
  - action: aws:runShellScript
    name: runShellScript
    inputs:
      timeoutSeconds: "5"
      runCommand:
        - "#!/usr/bin/env bash"
        - "git status"
    precondition:
      StringEquals:
        - platformType
        - Linux
```
