### ISSUE TITLE
Better support for your own Amazon Linux please!

### ISSUE THREAD

**Issue by nikolay** [aws/amazon-ssm-agent#47]
This is my CloudFormation snippet and it should be working - stop advising people to download and run (one time!) your `.rpm`/`.deb` file when your own distro already has the package:

```YAML
packages:
  yum:
    amazon-ssm-agent: []
services:
  sysvinit:
    amazon-ssm-agent:
      enabled: true
      ensureRunning: true
      packages:
        yum:
        - amazon-ssm-agent
      files:
      - /var/log/amazon/ssm/amazon-ssm-agent.log
      - /var/log/amazon/ssm/error.log
```
